### ISSUE TITLE
Other resource field should have two fields

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#1]
In addition to a link to the other resource document, please add an open field for a short description of the resource contained at the link. The description field should be optional.

**Comment by rheaplex** [comment]
We currently have the field "Summary of Elements of Resource Relevant to Reversionary Rights", which I think covers this?

**Comment by peterspdx** [comment]
Ah, that's a good catch. Let's use that field for the time being. Thanks,
Rob!

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by rheaplex** [comment]
Cool. If we need to refactor this later obviously we can do so.

Thank you!
