### ISSUE TITLE
clean up on the U.S. information page

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#11]
Once the new content is included as approved today, there is additional clean up the I am uncertain how to handle.

* Delete the phrase at the top "Termination of transfer tool for the US at ..." because that's now in the resource section below (once the commit request is acted upon).

* Delete the period after Brianna's name at the bottom

* For any field without submitted content, such as the Bills section, we need to have the statement rather than leaving it blank: "No information provided."

**Comment by rheaplex** [comment]
1. Deleted.
2. This is an artefact of the way lists are formatted. The eventual format will be:
    Ryan Merkley, Rob Myers, Diane Peters.
with commas separating names and a period terminating the list. I can remove the period in general if desired.
3. I can remove empty sections, which might be more aesthetically pleasing.

Let me know your preferences on 2 and 3.

**Comment by peterspdx** [comment]
fine to leave period, now I understand.

Leave empty sections, don't worry about the filler text. I liked the Stanford example where they included text re "no information" or similar, but for now leave as is.

**Comment by rheaplex** [comment]
OK will do. It is possible to add filler text, we can do that later.
