### ISSUE TITLE
Activate link to court case for Netherlands

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#16]
The link to the Supreme Court decision ‘Nanada Music B.V.’ does not seem to work. Would you please ask to have it activated? The reference is this one: https://uitspraken.rechtspraak.nl/inziendocument?id=ECLI:NL:HR:2017:1270

**Comment by rheaplex** [comment]
This is a frustrating bug in the site generator.

If the string we are generating a filename from ends in a period, e.g. inc. or b.v. , an html file rather than a directory is created. I will work out how to fix this.

**Comment by rheaplex** [comment]
Fixed in 7f294ad .
