### ISSUE TITLE
Fixes to Canada page

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#17]
the link for section 14 of the Copyright Act leads to the content for section 60, need to fix

link for Anne of Green Gables Licensing Authority Inc. v. Avonlea Traditions Inc. is broken

link for Desmarais c. Edimag Inc. is broken

link for "See Summary" on the paywalled resources entry is broken

@robmyers Let me know if we need to talk through any of these. Thx.

**Comment by rheaplex** [comment]
I've just pulled the latest changes and redeployed. Were there fixes for these in the current spreadsheet or are these changed I need to make? Thank you.

**Comment by rheaplex** [comment]
The inc. links are the same bug as #16 . This looks nasty and may not get fixed today.

The copyright act links may be a result of having two entries with the same name? Try appending the year or entry section to the title.

**Comment by rheaplex** [comment]
I found a hacky fix for the cases ending in "inc." that probably makes the filenames more correct anyway. 7f294ad

**Comment by rheaplex** [comment]
Changing the names of the Candian Copyright Law entries fixed it.

This means that entries of each type (case, legislation, etc.) for a given country require unique names.
