### ISSUE TITLE
Need link to submission form on home page and on country page (US as sample) to create a new country page or add to an existing page 

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#2]
As described. At present, there's no way to get a user from the home page or the current sample country page (United States) to the form where fields are completed and submitted to the different spreadsheets. Please add so we can have the initial submitters set up example pages.

**Comment by rheaplex** [comment]
I don't think we need a request-a-country page, people submit resources and we create a page for them. However we could create empty pages for all the countries? That would work well if we can add form links to the bottom of each page. I just want to avoid having a few pages, with some having content on and some not and no way to tell which is which.

The current build has the forms linked from a page called "Contribute":

https://labs.creativecommons.org/reversionary-rights/contribute/

Having links to add resources on each page is a very good idea, I'll see if we can pre-populate the country field in the form.

**Comment by rheaplex** [comment]
The country pages now have a block of links at the bottom to add new resources.

These link to the forms, with the country field pre-selected.

**Comment by peterspdx** [comment]
+1
