### ISSUE TITLE
Correct a few typos on home page

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#3]
Current: "While these arrangements may sometimes be profitable in the beginning -- "

Change to: "While these arrangements may sometimes be profitable in the beginning for authors --"

Current: "Many authors and creators give away control over their rights." 

Change to: "Many authors and creators give away control over their rights as part of the publication process."

Current: "Click on the map below or use our search box to learn more..."

Change to: "Click on the map below to use our search box to learn more...." [The change being from "or" to "to"]

**Comment by rheaplex** [comment]
You can edit this here:

https://github.com/creativecommons/reversionary-rights/edit/master/jekyll/index.html

**Comment by rheaplex** [comment]
Fixed in 7273f9b .

Deployed to test site.

Thank you!
