### ISSUE TITLE
Create informative design for homepage

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/reversionary-rights#4]
@little-wow on point for securing designer and communicating needs along with Diane.

**Comment by rheaplex** [comment]
Some notes of caution:

1. Anything we cannot simply add to the Jekyll site will cause us to miss our initial deadline.

2. Anything we receive needs to either be HTML(/css/js) that works with our Jekyll theme and content, or a Jekyll theme that works with our content.

3. Anything we receive needs to be a clean GitHub merge request if it is to be added to the existing repository, or a public Git repository with code licensed under the MIT or GPLv3+ licenses .

**Comment by little-wow** [comment]
What's the deadline on this?

**Comment by peterspdx** [comment]
@little-wow You indicated in our call last week it could be done before Summit, but if not so long as it's by first part of June is fine. We do want to make the landing page prettier so if you could please look at text and see what you think could be done there that would be great. Let us know.

**Comment by little-wow** [comment]
Are there design specs that I can pass along? I saw the model of the Stanford site, but I'd love to know what you are looking for? Something similar to what she created last time?

**Comment by peterspdx** [comment]
@little-wow Along the lines of what we did last time. A progression chart would be terrific. Let's set up a time to discuss, sending invite next.

**Comment by peterspdx** [comment]
completed for Summit.
